
#  CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  test:
    docker:
      # specify the version
      - image: cimg/go:1.20.0
      - image: hashicorp/consul
      - image: gcr.io/etcd-development/etcd:v3.5.1

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: bash gofmt.sh
      - run: go vet ./...
      - run: go test -v ./...

  race:
    docker:
      # specify the version
      - image: cimg/go:1.20.0
      - image: hashicorp/consul
      - image: gcr.io/etcd-development/etcd:v3.5.1

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -t -d ./...
      - run:
          command: go test -v -race ./...
          environment:
                GORACE: "halt_on_error=1"

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - race

